apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: argocd-grpc-route
  namespace: argocd
spec:
  parentRefs:
  - name: homelab-gateway
    namespace: default
  hostnames:
  - "argocd-grpc.thorntoncloud.com"
  rules:
  - matches:
    - method:
        type: RegularExpression
        service: ".*"
    backendRefs:
    - name: argocd-server-grpc
      port: 443